from musica import Musica
array_Musicas = [
Musica('Speak to Me', 'Pink Floyd - The Dark Side of the Moon', 1973, 1),
Musica('Breathe', 'Pink Floyd - The Dark Side of the Moon', 1973, 2),
Musica('On the Run', 'Pink Floyd - The Dark Side of the Moon', 1973, 3),
Musica('Time', 'Pink Floyd - The Dark Side of the Moon', 1973, 4),
Musica('Pink Floyd - The Great Gig in the Sky', 'Pink Floyd - The Dark Side of the Moon', 1973, 5),
Musica('Money', 'Pink Floyd - The Dark Side of the Moon', 1973, 6),
Musica('Us and Them', 'Pink Floyd - The Dark Side of the Moon', 1973, 7),
Musica('Any Colour You Like', 'Pink Floyd - The Dark Side of the Moon', 1973, 8),
Musica('Brain Damage', 'Pink Floyd - The Dark Side of the Moon', 1973, 9),
Musica('Eclipse', 'Pink Floyd - The Dark Side of the Moon', 1973, 10),
Musica("Oceans", "Pearl Jam - MTV Unplugged", 1992, 11),
Musica("State of love and trust", "Pearl Jam - MTV Unplugged", 1992, 12),
Musica("Alive", "Pearl Jam - MTV Unplugged", 1992, 13),
Musica("Black", "Pearl Jam - MTV Unplugged", 1992, 14),
Musica("Jeremy", "Pearl Jam - MTV Unplugged", 1992, 15),
Musica("Porch", "Pearl Jam - MTV Unplugged", 1992, 16),
Musica("Even Flow", "Pearl Jam - MTV Unplugged", 1992, 17),
Musica("Rockin' in the Free World", "Pearl Jam - MTV Unplugged", 1992, 18),
Musica("Sou + você", "Racionais MC's - Nada como um dia apos o outro", 2002, 19),
Musica("Vivão e vivendo", "Racionais MC's - Nada como um dia apos o outro", 2002, 20),
Musica("Vida Loka (Intro)", "Racionais MC's - Nada como um dia apos o outro", 2002, 21),
Musica("Vida loka, Pt. 1", "Racionais MC's - Nada como um dia apos o outro", 2002, 22),
Musica("Negro Drama", "Racionais MC's - Nada como um dia apos o outro", 2002, 23),
Musica("A vítima", "Racionais MC's - Nada como um dia apos o outro", 2002, 24),
Musica("Na fé firmão", "Racionais MC's - Nada como um dia apos o outro", 2002, 25),
Musica("12 de Outubro", "Racionais MC's - Nada como um dia apos o outro", 2002, 26),
Musica("Eu sou 157", "Racionais MC's - Nada como um dia apos o outro", 2002, 27),
Musica("A vida é desafio", "Racionais MC's - Nada como um dia apos o outro", 2002, 28),
Musica("1 por Amor, 2 por dinheiro", "Racionais MC's - Nada como um dia apos o outro", 2002, 29),
Musica("Welcome to the Jungle", "Guns & Roses - Appetite for Destruction", 1987, 30),
Musica("It`s So Easy", "Guns & Roses - Appetite for Destruction", 1987, 31),
Musica("Nightrain", "Guns & Roses - Appetite for Destruction", 1987, 32),
Musica("Out Ta get Me", "Guns & Roses - Appetite for Destruction", 1987, 33),
Musica("Mr. Brownstone", "Guns & Roses - Appetite for Destruction", 1987, 34),
Musica("Paradise City", "Guns & Roses - Appetite for Destruction", 1987, 35),
Musica("My Michelle", "Guns & Roses - Appetite for Destruction", 1987, 36),
Musica("Think About You", "Guns & Roses - Appetite for Destruction", 1987, 37),
Musica("You're Crazy", "Guns & Roses - Appetite for Destruction", 1987, 38),
Musica("Sweet Child O' Mine", "Guns & Roses - Appetite for Destruction", 1987, 39),
Musica("Anything Goes", "Guns & Roses - Appetite for Destruction", 1987, 40),
Musica("Rocket Queen", "Guns & Roses - Appetite for Destruction", 1987, 41),
Musica("Wanna Be Startin'Somethin", "Michael Jackson - Thriller", 1982, 42),
Musica("Baby Be Mine", "Michael Jackson - Thriller", 1982, 43),
Musica("The Girl is Mine", "Michael Jackson - Thriller", 1982, 44),
Musica("Thriller", "Michael Jackson - Thriller", 1982, 45),
Musica("Beat It", "Michael Jackson - Thriller", 1982, 46),
Musica("Billie Jean", "Michael Jackson - Thriller", 1982, 47),
Musica("Human Nature", "Michael Jackson - Thriller", 1982, 48),
Musica("P.Y.T (Pretty Young Thing)", "Michael Jackson - Thriller", 1982, 49),
Musica("The Lady in My Life", "Michael Jackson - Thriller", 1982, 50),
Musica("Let's stay together", "Al green - Let's stay together", 1971, 51),
Musica("Kiss and say goodbye", "The Manhattans", 1976, 52),
Musica("Reasons", "Earth, Wind & Fire - That's the Way of the World", 1974, 53),
Musica("Let's Get It On", "Marvin Gaye - Let's Get It On", 1973, 54),
Musica("Superstition", "Stevie Wonder - Talking Book", 1972, 55),
Musica("The payback", "James Brown - The Payback", 1980, 56),
Musica("Love man", "Ottis Regging - Love man", 1969, 57)
]

